services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Health\Application\Service\GetHealthStatusService: ~

    App\Health\Infrastructure\Http\Controller\HealthController:
        tags: ['controller.service_arguments']
