services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    App\Shared\Infrastructure\Http\Controller\HealthController:
        tags: ['controller.service_arguments']
